FROM python:3.12-slim

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Set shared directory first
WORKDIR /app/shared
COPY app/shared /app/shared

# Set working directory for the web app
WORKDIR /app/web
COPY app/web /app/web

# Set environment variables
ENV PYTHONPATH="/"

# Install Python dependencies
COPY app/web/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8000

# Run the application with our startup script
#CMD ["/entrypoint.sh"]
#ENTRYPOINT ["python", "-m", "app.shared.web.infrastructure.entrypoint", "web"]
CMD python -m app.shared.web.infrastructure.entrypoint && python -m app.web.core.main