FROM python:3.9-slim

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Set shared directory first
WORKDIR /app/shared
COPY app/shared /app/shared

# Copy both bot and web code (for testing both)
WORKDIR /app/bot
COPY app/bot /app/bot
WORKDIR /app/web
COPY app/web /app/web

# Set tests directory 
WORKDIR /app/tests
COPY app/tests /app/tests

# Set environment variables
ENV PYTHONPATH="/"

# Install all dependencies for testing
COPY app/bot/requirements.txt /app/bot/requirements.txt
COPY app/web/requirements.txt /app/web/requirements.txt
RUN pip install --no-cache-dir -r /app/bot/requirements.txt \
    && pip install --no-cache-dir -r /app/web/requirements.txt

# Set working directory to tests
WORKDIR /app/tests

# Add these lines to your Dockerfile.bot
RUN mkdir -p /tmp && chmod 777 /tmp

# Set an environment variable to tell pytest not to use file capturing
ENV PYTEST_ADDOPTS="--capture=no"

# Keep container running
CMD ["tail", "-f", "/dev/null"]