services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    image: foundrycord-bot:latest
    container_name: foundrycord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - ENABLED_SERVICES=${ENABLED_SERVICES:-Web,Game,File}
      - OFFLINE_MODE=${OFFLINE_MODE:-false}
      - SESSION_DURATION_HOURS=${SESSION_DURATION_HOURS:-24}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-60}
      - RATE_LIMIT_MAX_ATTEMPTS=${RATE_LIMIT_MAX_ATTEMPTS:-5}
      - PUID=${PUID:-1001}
      - PGID=${PGID:-987}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    networks:
      - discord-net
    dns:
      - 1.1.1.1
    volumes:
      - ../../../vpn-management/wireguard/config/:/app/bot/database/wireguard
      - /var/run/docker.sock:/var/run/docker.sock
      - bot_config:/app/bot/config
      - /etc/localtime:/etc/localtime:ro
      - ../app/shared:/app/shared
      - ../app/bot:/app/bot
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_healthy
        
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    image: foundrycord-web:latest
    container_name: foundrycord-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ../app/web:/app/web
      - ../app/shared:/app/shared
    networks:
      - discord-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    container_name: foundrycord-db
    restart: unless-stopped
    env_file:
      - .env
    command: ["postgres", "-c", "listen_addresses=*"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./postgres/init-tables.sql:/docker-entrypoint-initdb.d/init-tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -d foundrycord -c 'SELECT 1 FROM pg_database'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - discord-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  redis:
    image: redis:alpine
    container_name: foundrycord-cache
    restart: unless-stopped
    networks:
      - discord-net
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  discord-net:
    name: foundrycord-network
    driver: bridge
  proxy:
    external: true

volumes:
  postgres_data:
    driver: local
  bot_config:
    driver: local
  bot_credentials:
    driver: local
  redis_data:
    driver: local 