services:
  bot:
    build:
      context: .
      dockerfile: ../app/bot/Dockerfile
    image: homelab-discord-bot:latest
    container_name: homelab-discord-bot
    restart: unless-stopped
    env_file:
      - .env.discordbot
      - .env.postgres
    networks:
      - homelab-net
    dns:
      - 1.1.1.1
    volumes:
      - ../app/bot/:/app/bot/
      - ../../../vpn-management/wireguard/config/:/app/bot/database/wireguard
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
    # Benutzer kann hier überschrieben werden, wenn nötig
    # user: "1004:987"

  postgres:
    image: postgres:17-alpine
    container_name: homelab-postgres
    restart: unless-stopped
    env_file:
      - .env.postgres
    command: ["postgres", "-c", "listen_addresses=*"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - homelab-net

networks:
  homelab-net:
    driver: bridge
  proxy:
    external: true

volumes:
  postgres_data:
    driver: local
