name: Run Tests

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends gcc build-essential
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Use your specific requirements files
          pip install -r app/bot/requirements.txt
          pip install -r app/web/requirements.txt
          # Install test dependencies
          pip install pytest pytest-asyncio pytest-cov
      
      - name: Run unit tests
        run: |
          cd app
          python -m pytest tests/unit -v --capture=no
      
      - name: Run integration tests
        # Only run if unit tests pass
        if: success()
        run: |
          cd app
          python -m pytest tests/integration -v --capture=no
          
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()  # Upload test results even if tests fail
        with:
          name: test-results
          path: app/tests/test-results/ 